brain_two/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path(
        "",
        RedirectView.as_view(url="todos"),
        name="home",
    ),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListDetailView,
    TodoListView,
    CreateTodoListView,
    UpdateTodoListView,
    DeleteTodoListView,
    CreateTodoItemView,
    UpdateTodoItemView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todos_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_detail"),
    path("create/", CreateTodoListView.as_view(), name="todolist_new"),
    path("<int:pk>/edit/", UpdateTodoListView.as_view(), name="todolist_edit"),
    path(
        "<int:pk>/delete/", DeleteTodoListView.as_view(), name="todolist_delete"
    ),
    path("items/create/", CreateTodoItemView.as_view(), name="todoitem_new"),
    path(
        "items/<int:pk>/edit/",
        UpdateTodoItemView.as_view(),
        name="todoitem_edit",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return self.task

todos/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


from todos.models import TodoList, TodoItem


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class CreateTodoListView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    fields = ["name"]
    success_url = reverse_lazy("todos_list")


class UpdateTodoListView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]
    success_url = reverse_lazy("todos_list")


class DeleteTodoListView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todos_list")


class CreateTodoItemView(CreateView):
    model = TodoItem
    template_name = "items/new.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todos_list")


class UpdateTodoItemView(UpdateView):
    model = TodoItem
    template_name = "items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todos_list")

todos/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To Do List</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'todos_list' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'todolist_new' %}">Create List</a>
        </li>
        <li>
          <a href="{% url 'todoitem_new' %}">Create a Todo Item</a>
        </li>
      </ul>
    </nav>
  </header>
  {% block content %}
  {% endblock content %}
</body>
{% block pagination %}
{% endblock pagination %}

</html>

todos/templates/items/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<p>This is the EDIT todo list ITEM page</p>
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button>Create</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/items/new.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<p>This is the CREATE todo list ITEM page</p>
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button>Create</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ todolist.name }}"?</p>
    {{ form.as_p }}
    <div>
      <button>Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content%}
<main>
  <div>
    <a href="{% url 'todolist_edit' todolist.id %}">Edit Todo List</a>
    <a href="{% url 'todolist_delete' todolist.id %}">Delete Todo List</a>
  </div>
  <h1>{{todolist.name}} Todo List</h1>
  <p>Created on {{todolist.created_on}}</p>
  <table>
    <thead>
      <th>Todo List Items</th>
      <!-- <th>Due on</th> -->
    </thead>
    <tbody>
      {% for list_item in todolist.items.all %}
      <tr>
        <td><a href="{% url 'todoitem_edit' list_item.id %}">
            {{ list_item.task }}</a></td>
        <!-- <td>{{ list_item.due_date}}</td> -->
      </tr>

      {% endfor %}
    </tbody>
  </table>
  <div>

  </div>
</main>
{% endblock content %}

todos/templates/todos/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<p>This is the EDIT todo list page</p>
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button>Create</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %}

{% load static %}

{% block content%}
<main>
  <ul>
    {% for todo_list in todolist_list %}
    <a href="{% url 'todo_detail' todo_list.pk %}">{{todo_list.name}}</a>
    {% endfor %}
  </ul>


</main>
{% endblock content %}

todos/templates/todos/new.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<p>This is the new todo list page</p>
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button>Create</button>
    </div>
  </form>
</main>
{% endblock content %}